name: fzu_qrcode
description: "因为懒得使用福大一码通小程序，所以写了个app"
publish_to: "none"
version: 0.1.2+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  qr_flutter: ^4.0.0
  provider: ^6.0.0
  path_provider: ^2.0.11
  dio: ^5.0.0
  cupertino_icons: ^1.0.6
  flutter_launcher_icons: ^0.9.2
  url_launcher: ^6.0.6
# 图标
# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: true
  ios: true
  Windows: true
  image_path: "assets/icon/icon.jpg"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
# flutter资源文件
flutter:
  uses-material-design: true
  fonts:
    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/JetBrainsMono-Regular.ttf
        - asset: assets/fonts/JetBrainsMono-Bold.ttf
          weight: 700
        - asset: assets/fonts/JetBrainsMono-Italic.ttf
          style: italic
        - asset: assets/fonts/JetBrainsMono-BoldItalic.ttf
          weight: 700
          style: italic
