name: Build APK

on:
  pull_request:
    types: [closed]
    branches: [main]
    paths-ignore:
      - "*.md"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 设置 Java 17
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: "adopt"
          java-version: "17"

      # 设置 Flutter 环境
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      # 安装依赖
      - name: Get dependencies
        run: flutter pub get

      # 构建并签名 APK
      - name: Build and Sign APK
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          echo $KEYSTORE_BASE64 | base64 --decode > android/app/keystore.jks
          export KEYSTORE_PATH=keystore.jks
          flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi

      # 上传 APKs
      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: apks
          path: build/app/outputs/flutter-apk/*.apk
